meta_product_name: "Product Name"
meta_title: "Petsies - Nos compagnons de vie méritent notre attention"
meta_description: "Petsies l'app qui te permet de suivre facilement les activités, rendez-vous et traitement de tes animaux préférés"
meta_image: "og_logo.png"
